spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306/${MYSQL_DATABASE:sc-mh_dev}}?characterEncoding=utf-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS}
    # 加载驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 声明数据库连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enable: true
    liverload:
      enabled: true

  application:
      name: springboot-mybatis-swagger

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss

server:
# 访问端口
  port: 8081

# 整合mybatis
mybatis:
  #  声明映射路径
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.chenjy.mybatis.demo.entity  # 注意：对应实体类的路径
  configuration:
      map-underscore-to-camel-case: true
##
## druid配置
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#
